---
- name: Enable Filebeat service
  become: true
  service:
    name: filebeat
    state: started
    enabled: yes
- name: Configurure Filebeat
  become: true
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
    mode: 0640
  notify: restart Filebeat
