---
- name: Converge
  hosts: elk
  roles:
    - elasticsearch-role
    - logstash-role

- name: Converge
  hosts: kbn
  tasks:
    - name: "Include kibana-role"
      include_role:
        name: "kibana-role"

- name: Converge
  hosts: fbt
  tasks:
    - name: "Include filebeat-role"
      include_role:
        name: "filebeat-role"
